/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiBudget;

import guiBudget.*;
import databaseBudget.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class frmDashboard extends javax.swing.JFrame {

    
    /**
     * Creates new form frmDashboard
     */
    public String loggedinuname="";
    public frmDashboard() {
        initComponents();
        menuDashboard.setEnabled(false);

    }
    
    //Seperate constructor to have the dashboard page have a username 
    public frmDashboard(String uname) {
        initComponents();
        this.loggedinuname = uname; 
        menuDashboard.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profileBox = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDashboard = new javax.swing.JMenu();
        menuTransactions = new javax.swing.JMenu();
        menuItems = new javax.swing.JMenu();
        menuProfile = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Homepage");

        jLabel2.setText("Total Expense of the Month so far...");

        profileBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profile", "Log Out?", "Delete Account" }));
        profileBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBoxActionPerformed(evt);
            }
        });

        menuDashboard.setText("Dashboard");
        menuDashboard.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuDashboardMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuDashboard);

        menuTransactions.setText("Transactions");
        menuTransactions.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuTransactionsMenuSelected(evt);
            }
        });
        menuTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransactionsActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuTransactions);

        menuItems.setText("Items");
        menuItems.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuItemsMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuItems);

        menuProfile.setText("My Profile");
        menuProfile.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuProfileMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuProfile);

        menuHelp.setText("Help");
        menuHelp.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuHelpMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196)
                        .addComponent(profileBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(237, 237, 237))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(profileBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //Creating new database object to be able to run the methods
    dbBudget d1 = new dbBudget();       
 
    
    private void profileBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBoxActionPerformed
        // TODO add your handling code here:
        
       //Checking whether the user clicks "Log out?" or "Delete Account"
       String selectedValue = profileBox.getSelectedItem().toString();
       System.out.println(selectedValue);
       System.out.println(this.loggedinuname);
       //Takes the user back to the log in page 
        if(selectedValue.equalsIgnoreCase("Log out?") == true){
            new frmLogin().setVisible(true);
            this.dispose();
        }
        
        //Removes the value from the User_Info database such that this cannot be logged into again when attempted
        if(selectedValue.equalsIgnoreCase("Delete Account") == true){
            try {
                //Runs the database delete record method from the dbBudget class              
                d1.deleteDBRecord(loggedinuname);
                
                //Opens login page and closes dashboard 
                new frmLogin().setVisible(true);
                this.dispose();
              //If try block does not work
            } catch (SQLException ex) {
                Logger.getLogger(frmDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }                      
        } 
        
    }//GEN-LAST:event_profileBoxActionPerformed

    private void menuTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransactionsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuTransactionsActionPerformed

    private void menuTransactionsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuTransactionsMenuSelected
        // TODO add your handling code here:
        new frmTransactionList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuTransactionsMenuSelected

    private void menuItemsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuItemsMenuSelected
        // TODO add your handling code here:
        new frmItems().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemsMenuSelected

    private void menuProfileMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuProfileMenuSelected
        // TODO add your handling code here:
        new frmProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuProfileMenuSelected

    private void menuHelpMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuHelpMenuSelected
        // TODO add your handling code here:
        new frmHelp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuHelpMenuSelected

    private void menuDashboardMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuDashboardMenuSelected
        // TODO add your handling code here:
        new frmDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuDashboardMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDashboard().setVisible(true);
            }
        });
    }

    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuDashboard;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuItems;
    private javax.swing.JMenu menuProfile;
    private javax.swing.JMenu menuTransactions;
    private javax.swing.JComboBox<String> profileBox;
    // End of variables declaration//GEN-END:variables
}
