/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiBudget;

import budgetApp.ClsItems;
import budgetApp.*;
import databaseBudget.*;
import java.util.ArrayList;

/**
 *
 * @author mohammadzuhayrkabir
 */
public class frmItems extends javax.swing.JFrame {

    /**
     * Creates new form frmItems
     */
    
    ArrayList<ClsItems> items = new ArrayList<ClsItems>();
    
    

    public frmItems() {
        initComponents();
        LoadItems();
        menuItems.setEnabled(false);
        
    }
    
    public boolean LoadItems()
    {
        //connect to database 
        
        //get each items row
        
        //populate the items object
        
        //add the object to the arraylist
        
        return true; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuDashboard = new javax.swing.JMenu();
        menuTransactions = new javax.swing.JMenu();
        menuItems = new javax.swing.JMenu();
        menuProfile = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuDashboard.setText("Dashboard");
        menuDashboard.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuDashboardMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuDashboard);

        menuTransactions.setText("Transactions");
        menuTransactions.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuTransactionsMenuSelected(evt);
            }
        });
        menuTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransactionsActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuTransactions);

        menuItems.setText("Items");
        menuItems.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuItemsMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuItems);

        menuProfile.setText("My Profile");
        menuProfile.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuProfileMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuProfile);

        menuHelp.setText("Help");
        menuHelp.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuHelpMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTransactionsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuTransactionsMenuSelected
        // TODO add your handling code here:
        new frmTransactionList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuTransactionsMenuSelected

    private void menuTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransactionsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuTransactionsActionPerformed

    private void menuItemsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuItemsMenuSelected
        // TODO add your handling code here:
        new frmItems().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemsMenuSelected

    private void menuProfileMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuProfileMenuSelected
        // TODO add your handling code here:
        new frmProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuProfileMenuSelected

    private void menuHelpMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuHelpMenuSelected
        // TODO add your handling code here:
        new frmHelp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuHelpMenuSelected

    private void menuDashboardMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuDashboardMenuSelected
        // TODO add your handling code here:
        new frmDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuDashboardMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuDashboard;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuItems;
    private javax.swing.JMenu menuProfile;
    private javax.swing.JMenu menuTransactions;
    // End of variables declaration//GEN-END:variables
}
