/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiBudget;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

import databaseBudget.*;
import budgetApp.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mohammadzuhayrkabir
 */
public class frmTransactionList extends javax.swing.JFrame {
    String ItemName;

    dbBudget d1 = new dbBudget(); 

    /**
     * Creates new form frmTransactionList
     */
    public frmTransactionList() {
        initComponents();
        menuTransactions.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblExpenses = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        addNewTransaction = new javax.swing.JButton();
        filterTransaction = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDashboard = new javax.swing.JMenu();
        menuTransactions = new javax.swing.JMenu();
        menuItems = new javax.swing.JMenu();
        menuProfile = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Transaction_ID", "Transaction_Name", "Transaction_Amount", "UserID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblExpenses);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addNewTransaction.setText("Add New Transaction");
        addNewTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewTransactionActionPerformed(evt);
            }
        });

        filterTransaction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter by:", "Item 2", "Item 3", "Item 4" }));

        menuDashboard.setText("Dashboard");
        menuDashboard.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuDashboardMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuDashboard);

        menuTransactions.setText("Transactions");
        menuTransactions.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuTransactionsMenuSelected(evt);
            }
        });
        menuTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransactionsActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuTransactions);

        menuItems.setText("Items");
        menuItems.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuItemsMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuItems);

        menuProfile.setText("My Profile");
        menuProfile.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuProfileMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuProfile);

        menuHelp.setText("Help");
        menuHelp.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuHelpMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addNewTransaction)
                .addGap(84, 84, 84)
                .addComponent(jButton1)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filterTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(addNewTransaction))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTransactionsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuTransactionsMenuSelected
        // TODO add your handling code here:
        new frmTransactionList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuTransactionsMenuSelected

    private void menuTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransactionsActionPerformed
        // TODO add your handling code here:the 
        
    }//GEN-LAST:event_menuTransactionsActionPerformed

    private void menuItemsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuItemsMenuSelected
        // TODO add your handling code here:
        new frmItems().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemsMenuSelected

    private void menuProfileMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuProfileMenuSelected
        // TODO add your handling code here:
        new frmProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuProfileMenuSelected

    private void menuHelpMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuHelpMenuSelected
        // TODO add your handling code here:
        new frmHelp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuHelpMenuSelected

    private void menuDashboardMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuDashboardMenuSelected
        // TODO add your handling code here:
        new frmDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuDashboardMenuSelected

    
    
    
    
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try
        {
            List<ClsTransaction> data= (List<ClsTransaction>) d1.loadAllTransactions();   //getting the data to show in the table
            
            DefaultTableModel jtblmodel = (DefaultTableModel)tblExpenses.getModel();   //table is made ready 
            jtblmodel.setRowCount(0);   //This is for refresh of the grid                        
            
            for (int i = 0; i < data.size(); i++) 
            {
                ClsTransaction tr = data.get(i);
                String TransactionID= String.valueOf(tr.getTransactionID());
                String TransactionName= tr.getTransactionName();
                String TransactionAmount = String.valueOf(tr.getTransactionAmount());
                String UserID = String.valueOf(tr.getUserID());
                
                //Creation an array to store the data to load in JTable
                String arrJtbl[] = {TransactionID,TransactionName,TransactionAmount,UserID};
                jtblmodel.addRow(arrJtbl);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


                      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addNewTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewTransactionActionPerformed
        // TODO add your handling code here:
        new frmTransactions().setVisible(true);
      //  this.dispose();
    }//GEN-LAST:event_addNewTransactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTransactionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTransactionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTransactionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTransactionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTransactionList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewTransaction;
    private javax.swing.JComboBox<String> filterTransaction;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuDashboard;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuItems;
    private javax.swing.JMenu menuProfile;
    private javax.swing.JMenu menuTransactions;
    private javax.swing.JTable tblExpenses;
    // End of variables declaration//GEN-END:variables
}
